# https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install plotly"

before_install:
   #- git clone --depth=50 --branch=master https://github.com/fredrik-johansson/flint2.git
   - git clone https://github.com/fredrik-johansson/flint2.git

#script: pytest
#script: make test
script: python python_test.py
