# https://docs.travis-ci.com/user/languages/python/

language: python
python:
  - "2.7"
# command to install dependencies
##install: "pip install plotly"

before_install:
  - "pwd"
  - "cd ~/"  
  - "pwd"

