# https://docs.travis-ci.com/user/languages/python/

dist: trusty

language: python
python:
  - "2.7"
# command to install dependencies
##install: "pip install plotly"

before_install:
   # GMP LIB
   - "wget https://gmplib.org/download/gmp/gmp-6.1.2.tar.bz2"
   - "tar -xvf gmp-6.1.2.tar.bz2"
   - "rm -f gmp-6.1.2.tar.bz2"
   - "cd ./gmp-6.1.2/"
   - "./configure"
   - "make"
   - "sudo make install"
   - "cd ../"
   # MPFR
   - "wget http://www.mpfr.org/mpfr-current/mpfr-3.1.5.tar.gz"
   - "tar -xvf mpfr-3.1.5.tar.gz"
   - "rm -f mpfr-3.1.5.tar.gz"
   - "cd ./mpfr-3.1.5/"
   - "./configure"
   - "make"
   - "sudo make install"
   - "cd ../"
   # FLINT2
   #- git clone --depth=50 --branch=master https://github.com/fredrik-johansson/flint2.git
   - "git clone https://github.com/fredrik-johansson/flint2.git"
   - "cd ./flint2/"
   - "./configure"
   - "make"
   - "sudo make install"
   - "cd ../"
   # ARB
   - "git clone https://github.com/fredrik-johansson/arb.git"
   - "cd ./arb/"
   - "./configure"
   - "make"
   - "sudo make install"
   - "cd ../"
   # python-flint
   - "sudo apt-get install cython python-dev"
   - "git clone https://github.com/fredrik-johansson/python-flint.git"
   - "cd ./python-flint"
   #- "sudo mkdir /usr/local/share/flint/"
   #- "sudo cp ~/build/mkarakoc/aim/flint2/qadic/CPimport.txt /usr/local/share/flint/CPimport.txt"
   #- "export LD_LIBRARY_PATH=~/build/mkarakoc/aim/flint2:~/build/mkarakoc/aim/arb:$LD_LIBRARY_PATH"
   - "export LD_LIBRARY_PATH=/usr/local/include/flint:/usr/local/include/arb:$LD_LIBRARY_PATH"
   #- "sudo python ./setup.py build_ext --include-dirs=~/build/mkarakoc/aim/flint2:~/build/mkarakoc/aim/arb --library-dirs=~/build/mkarakoc/aim/flint2:~/build/mkarakoc/aim/arb"
   - "sudo python ./setup.py build_ext --include-dirs=/usr/local/include/flint:/usr/local/include/arb --library-dirs=/usr/local/include/flint:/usr/local/include/arb"
   #- "sudo python setup.py build_ext"
   - "sudo python setup.py install"
   - "cd ../"
   
   
#script: pytest
#script: make test
script:
    - "pwd"
    - "sudo python python_test.py"

# END .travis.yml
